### ISSUE TITLE
Cannot build on Linux Mint 22.1

### ISSUE THREAD

**Issue by hopelessdecoy** [jewelcodes/tinygb#2]
Libraries installed with "libsdl" in name:
  **libsdl1.2debian 1.2.68-2 [Ubuntu/noble universe]
  libsdl2-2.0-0 2.30.0+dfsg-1build3 [Ubuntu/noble main]
  libsdl2-dev 2.30.0+dfsg-1build3 [Ubuntu/noble universe]**

I downloaded the code, unzipped the archive, cd into the directory and typed "make"

` [ CC ] src/log.o
 [ CC ] src/platform/sdl/main.o
 [ CC ] src/platform/sdl/tinyfiledialogs.o
 [ CC ] src/core/serial.o
 [ CC ] src/core/sound.o
 [ CC ] src/core/interrupts.o
 [ CC ] src/core/joypad.o
 [ CC ] src/core/cpu.o
 [ CC ] src/core/display.o
 [ CC ] src/core/memory.o
 [ CC ] src/core/timer.o
 [ CC ] src/core/mbc.o
 [ CC ] src/core/sgb.o
 [ CC ] src/core/cgb.o
 [ CC ] src/config.o
 [ LD ] tinygb
/usr/bin/ld: ./src/platform/sdl/main.o: in function `destroy_window':
main.c:(.text+0x610): undefined reference to `SDL_DestroyWindow'
/usr/bin/ld: ./src/platform/sdl/main.o: in function `update_window':
main.c:(.text+0x708): undefined reference to `SDL_UpdateWindowSurface'
/usr/bin/ld: ./src/platform/sdl/main.o: in function `resize_sgb_window':
main.c:(.text+0x7ff): undefined reference to `SDL_SetWindowSize'
/usr/bin/ld: main.c:(.text+0x815): undefined reference to `SDL_SetWindowPosition'
/usr/bin/ld: main.c:(.text+0x821): undefined reference to `SDL_GetWindowSurface'
/usr/bin/ld: ./src/platform/sdl/main.o: in function `delay':
main.c:(.text+0x5f5): undefined reference to `SDL_Delay'
/usr/bin/ld: ./src/platform/sdl/main.o: in function `destroy_window':
main.c:(.text+0x619): undefined reference to `SDL_Quit'
/usr/bin/ld: ./src/platform/sdl/main.o: in function `main':
main.c:(.text.startup+0x231): undefined reference to `SDL_Init'
/usr/bin/ld: main.c:(.text.startup+0x26a): undefined reference to `SDL_CreateWindow'
/usr/bin/ld: main.c:(.text.startup+0x282): undefined reference to `SDL_GetWindowSurface'
/usr/bin/ld: main.c:(.text.startup+0x294): undefined reference to `SDL_GetPixelFormatName'
/usr/bin/ld: main.c:(.text.startup+0x3a5): undefined reference to `SDL_UpdateWindowSurface'
/usr/bin/ld: main.c:(.text.startup+0x42c): undefined reference to `SDL_PollEvent'
/usr/bin/ld: main.c:(.text.startup+0x51d): undefined reference to `SDL_PollEvent'
/usr/bin/ld: main.c:(.text.startup+0x5dc): undefined reference to `SDL_SetWindowTitle'
/usr/bin/ld: main.c:(.text.startup+0x6e0): undefined reference to `SDL_DestroyWindow'
/usr/bin/ld: main.c:(.text.startup+0x6e5): undefined reference to `SDL_Quit'
/usr/bin/ld: main.c:(.text.startup+0x852): undefined reference to `SDL_GetError'
/usr/bin/ld: main.c:(.text.startup+0x879): undefined reference to `SDL_GetError'
/usr/bin/ld: main.c:(.text.startup+0x89b): undefined reference to `SDL_Quit'
collect2: error: ld returned 1 exit status
make: *** [Makefile:21: tinygb] Error 1
`

Would like to learn and work on a project with your program, let me know if I am doing anything wrong! I am assuming I have incorrect libs or the libs this uses are older. Thanks for any help!

**Comment by jewelcodes** [comment]
Hi!

The libraries you have installed and listed look correct and reasonable, and it seems this was mostly an issue from my end where I was assuming constant compiler and linker flags for all SDL installations. Sorry about that, it should be fixed now – try pulling the latest commit from the `build-system-fix` branch. This will require you to have the `sdl2-config` command in your path, so maybe check that that works too before trying to rebuild. I also pushed the default configuration file to serve as a starting point for customizing the emulator and to know which keys do what.

Let me know if it works or if you run into any other issues :)

**Comment by hopelessdecoy** [comment]
![Image](https://github.com/user-attachments/assets/b38a9d56-f3ed-49ad-9f18-51643a7d5f1a)

That branch builds and plays the most obscure ROM no one ever heard of lol

Would love to get sound working with this, then make a desktop packager for GB Studio games so people can create/play games created with it with "no emulator".

**Comment by jewelcodes** [comment]
Awesome, I've never heard of that ROM myself.

About the sound device or integrating this with something like GB Studio, I'm not really actively working on this anymore and so while those would be great to have, I probably won't implement them myself, but definitely feel free to fork the project and open a PR if you want :)
